langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: rpsfbnatL1eygWKYUSQ5Rr2o+BJot6G92z59vN/dtdlKT6Va2VcPdpsOJWBxwaapm7h2YdJl1NpxrpqLhgW8DaAnQPKPd1kiOJGYDOfNsIKmH+JUnIyyLR9nO3KKSFop+2UWxrbEHQNwKgencsVzbLPUx39sORMslgvvmJ7ty3YeLzWPDC8KqblUxhN0nQxZN52w5n2nmHbySGWLlzo//zVFFXcYfE+bRxBoQ2jlKx8f5PycJK3abn3pSIYg2596T3LP8keu/AiFX/tn6mA9mJCTwvAhMqAwkz4YlYwwmx4mR9SCrpclj9z7pSDmuKnuPalWqybJvjtEagA3PWlFiwctYUNcoKmrbEEtDm5C+GXhF31bbmqq5EuMYzEUGflwtvYjc3FKvC0yG1mjDWTilih/9DI7q2uYWgAob9IMRbSpxeCTLj4k2xjdpGAKcwmNYhoeJCpocacy8KOLa0nK7F+aYJAj4DUlJQ3lo5uDRc3QkyJT6FkH078Odwd5jRoow++uk/yxwHBb6DoS7iYJuIJ4mlfF9j6T9pE92O8k/vTeZtn+llaoRrZZdqMM8PXqG4kHrMuMoSiwiA1IgUxzW8YQRbSmrvZn3cc6ZFguQxO4QW7NV7Ttr3dMEOcfeTJlLydq7dujm8lu7VMqsLUVbm3MqydKu6u8JsV68bt9gyI=
  app: secure-fjord-62840
  run: rails db:migrate
